'use client';
import {useState} from 'react';
import {ArrowDown,ArrowUpRight,Menu,X,Mail,Plus,Minus} from 'lucide-react';
const work=[['Privacy exceptions and the GATS necessity test','Analyzing the Schrems I and II judgments and the EU–US Data Privacy Framework through GATS Article XIV’s general exceptions clause and necessity test.','Research in progress'],['Asia-Pacific digital governance','Exploring regional rule-making through DEFA and policy capacity gaps that influence implementation.','Research interest'],['EU digital regulation reporting','Reported on EU environmental and digital regulations and their impact on Korean exporters.','MoneyToday · 2024'],['Cross-cultural field leadership','Coordinated communication, schedules, and problem-solving in Tanzania and the Philippines.','International experience']];
const areas=[['GATS framework','General exceptions · Necessity test'],['Data governance','Cross-border data flows · Privacy'],['Regional rule-making','DEFA · Asia-Pacific capacity']];
export default function Home(){const [open,setOpen]=useState(0);const [menu,setMenu]=useState(false);return <main><a className="skip" href="#about">Skip to content</a><header><a className="logo" href="#top">Jieun<br/>Kim<span>·</span></a><nav className={menu?'open':''}>{['Work','About','Focus','FAQ'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<a className="nav-cta" href="#contact">Contact</a></nav><button className="hamburger" aria-label="Toggle menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<section id="top" className="hero"><div className="mini-label">WTO DIGITAL TRADE · SEOUL</div><div className="avatar" aria-label="Jieun Kim monogram">JK</div><h1><span>Hi, I&apos;m</span> Jieun Kim.</h1><p>I research the rules that help digital trade, data governance, and public interest move forward together.</p><a className="down" href="#work" aria-label="Explore portfolio"><ArrowDown size={19}/></a><div className="hero-line">GATS / DATA / GOVERNANCE / RESEARCH</div></section>
<section id="work" className="section"><p className="kicker">// SELECTED WORK</p><h2>Questions with real-world weight.</h2><p className="intro">A selection of current research, reporting, and cross-cultural work — built around clarity, rigor, and the people behind policy.</p><div className="work-grid">{work.map(([title,copy,tag],i)=><article className={'work-card tone-'+i} key={title}><div className="card-surface"><span>{String(i+1).padStart(2,'0')}</span><i>{i===0?'§ XIV':i===1?'DEFA':i===2?'EU':'15'}</i></div><div className="card-body"><small>{tag}</small><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
<section id="about" className="about-panel"><div><p className="kicker">// ABOUT</p><h2>Research that people can <em>use.</em></h2><p>Master&apos;s student at Seoul National University&apos;s Graduate School of International Studies, majoring in International Commerce (2026–2028).</p><p>My background in journalism, teaching, and international volunteering helps me translate complex regulations into useful questions and clear language.</p><a href="#contact" className="text-link">Start a conversation <ArrowUpRight size={15}/></a></div><div className="monogram-card"><b>JK</b><span>Digital trade<br/>researcher</span></div></section>
<section id="focus" className="services"><p className="kicker">// FOCUS AREAS</p><h2>Where I contribute.</h2><p className="intro">Legal analysis and policy research shaped for an increasingly connected economy.</p><div className="area-row">{areas.map(([a,b],i)=><article key={a}><b>0{i+1}</b><h3>{a}</h3><p>{b}</p></article>)}</div></section>
<section className="experience"><p className="kicker">// EXPERIENCE & EDUCATION</p><div className="exp-grid"><div><h2>Research-informed,<br/>field-tested.</h2><p>Experience across economic reporting, broadcast research, language education, and international team leadership.</p></div><ul><li><b>MoneyToday</b><span>Journalist Intern · 2024</span></li><li><b>MBC</b><span>Research Assistant · 2022</span></li><li><b>YBM</b><span>English Language Instructor · 2024–2026</span></li><li><b>Seoul National University</b><span>M.A. International Commerce · Expected 2028</span></li></ul></div></section>
<section id="faq" className="faq"><div><p className="kicker">// FAQ</p><h2>Questions I&apos;m working through.</h2><p>Explore the themes that guide my current research and career direction.</p></div><div>{['How do privacy rules work within global trade law?','What makes data-governance policy effective?','Why does regional digital rule-making matter?'].map((q,i)=><article key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{String(i+1).padStart(2,'0')}. {q}</span>{open===i?<Minus/>:<Plus/>}</button>{open===i&&<p>{i===0?'I examine GATS Article XIV and its general exceptions to understand how trade commitments and legitimate public-policy objectives can coexist.':i===1?'Effective policy attends to legal coherence, institutional capacity, and the everyday conditions needed for implementation.':'Regional frameworks can show how shared commitments become practical systems across different national contexts.'}</p>}</article>)}</div></section>
<footer id="contact"><div><p className="kicker">// CONTACT</p><h2>Ready for a thoughtful <em>conversation?</em></h2><p>For research conversations, collaboration, or a simple introduction, I&apos;d be glad to hear from you.</p><a className="mail" href="mailto:rldufwldms83@naver.com"><Mail size={17}/>rldufwldms83@naver.com</a></div><div className="contact-card"><span>JIEUN KIM</span><b>Digital Trade &<br/>Data Governance</b><a href="#top">Back to top <ArrowUpRight size={16}/></a></div><small>© 2026 Jieun Kim · Seoul, Republic of Korea</small></footer></main>}
